[package]
name = "clojure-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "clojure"

[dependencies]
which = "4.2.5"
anyhow = "1.0.62"
dunce = "1.0.2"
md-5 = "0.10"
